## 📊 Project Overview
This project analyzes e-commerce sales data using Python (Pandas)...

## 🎯 Business Objectives
- Analyze Revenue, Orders, AOV
- Identify top products & customers
- Perform trend analysis (MoM, YoY)

## ✅ Section Headers

- 📥 Data Loading
- 🧹 Data Cleaning
- 📊 Exploratory Data Analysis
- 📈 Trend Analysis
- 💡 Key Insights
- 🚀 Business Recommendations

# 📥 Data Loading

In [4]:
import pandas as pd

# Load the dataset
df = pd.read_excel("online_retail_II.xlsx")
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

# 🧹 Data Cleaning

In [ ]:
# 1. Checking for data types

df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

In [6]:
# 2. Checking for duplicates

duplicate_rows = df.duplicated().sum()
duplicate_rows

np.int64(6865)

In [7]:
# Removing duplicates

df = df.drop_duplicates()
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

In [8]:
# Checking again for duplicates after removal
duplicate_rows_after = df.duplicated().sum()
print("Number of Duplicate Rows after removal:", duplicate_rows_after)

Number of Duplicate Rows after removal: 0

In [9]:
# Checking for null values in each column
null_values = df.isnull().sum()
print("Null Values in each column:\n", null_values)

Null Values in each column:
 Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107833
Country             0
dtype: int64

In [10]:
# Dropping rows with null values

df = df.dropna()
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

In [11]:
# Rechecking for null values after dropping
null_values_after = df.isnull().sum()
print("Null Values in each column after dropping:\n", null_values_after)

Null Values in each column after dropping:
 Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [12]:
# Fixing data time columns
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['InvoiceDate'].dtype

C:\Users\dhamm\AppData\Local\Temp\ipykernel_3384\3664860657.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

dtype('<M8[ns]')

In [15]:
# Creating a new column for Total Price
df["TotalPrice"] = df['Quantity'] * df['Price']
df

C:\Users\dhamm\AppData\Local\Temp\ipykernel_3384\3131031102.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["TotalPrice"] = df['Quantity'] * df['Price']

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalPrice
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.40
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.00
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.00
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.80
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.00
...,...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom,5.90
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,3.75
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,3.75
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,7.50
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom,3.90

# 📊 Exploratory Data Analysis

In [20]:
# 1. Creating various Business KPIs

# 1.1. Total Revenues

total_revenue = df['TotalPrice'].sum()
print("Total Revenue: $", total_revenue)

Total Revenue: $ 8314855.584000001

In [21]:
# 1.2. Total Orders 
total_order = df['Invoice'].nunique()
print("Total Orders:", total_order)

Total Orders: 23587

In [22]:
# 1.3. Average Order Value
average_order_value = total_revenue/total_order
print("Average Order Value: $", average_order_value)

Average Order Value: $ 352.51857311230765

In [23]:
# 1.4. Top 10 Products by Quantity Sold
top_10_products_quantity = df.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(10)
print("Top 10 Products by Quantity Sold:\n", top_10_products_quantity)

Top 10 Products by Quantity Sold:
 Description
WHITE HANGING HEART T-LIGHT HOLDER    55760
WORLD WAR 2 GLIDERS ASSTD DESIGNS     54130
BROCADE RING PURSE                    47430
PACK OF 72 RETRO SPOT CAKE CASES      44480
ASSORTED COLOUR BIRD ORNAMENT         44000
60 TEATIME FAIRY CAKE CASES           35480
PACK OF 60 PINK PAISLEY CAKE CASES    30753
JUMBO BAG RED RETROSPOT               29439
BLACK AND WHITE PAISLEY FLOWER MUG    25679
SMALL POPCORN HOLDER                  25379
Name: Quantity, dtype: int64

In [24]:
# 1.5. Top 10 Customers by Total Price in countrywise.
top_10_customers = df.groupby(['Customer ID','Invoice','Country'])['TotalPrice'].sum().sort_values(ascending=False).head(10)
print("Top 10 Customers by Total Price in countrywise:\n", top_10_customers)

Top 10 Customers by Total Price in countrywise:
 Customer ID  Invoice  Country
14156.0      493819   EIRE              44051.60
17450.0      524181   United Kingdom    33167.80
18102.0      526934   United Kingdom    26007.08
             515944   United Kingdom    22863.36
             517731   United Kingdom    21984.00
14646.0      495591   Netherlands       18570.88
18102.0      494243   United Kingdom    18532.30
             531866   United Kingdom    18122.17
14156.0      515187   EIRE              17995.88
15838.0      530715   United Kingdom    17022.24
Name: TotalPrice, dtype: float64

# 📈 Trend Analysis

In [25]:
# 2.1. Monthly Sales Trends with pivot table Country wise

monthly_sales = df.pivot_table(index = 'Country',values='TotalPrice', columns= df['InvoiceDate'].dt.to_period('M'), aggfunc='sum').fillna(0)
monthly_sales

InvoiceDate,2009-12,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,2010-07,2010-08,2010-09,2010-10,2010-11,2010-12
Country,,,,,,,,,,,,,
Australia,50.25,0.000,1029.660,429.390,630.950,1312.70,3189.28,633.62,176.00,785.830,2989.15,18207.820,617.15
Austria,1998.34,0.000,1118.860,925.130,1388.540,582.04,268.10,0.00,1043.15,1589.120,1236.70,2873.300,0.00
Bahrain,0.00,0.000,0.000,0.000,0.000,488.21,0.00,0.00,0.00,0.000,317.76,0.000,0.00
Belgium,447.60,1624.070,1700.350,884.520,2549.140,84.95,3535.39,1914.23,1713.62,1190.060,1475.72,5178.280,346.10
Brazil,0.00,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.00,268.270,0.00,0.000,0.00
Canada,0.00,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.00,0.000,834.89,381.770,0.00
Channel Islands,945.38,822.850,0.000,130.460,926.820,5322.68,749.15,-33.00,1363.14,5271.340,4283.54,1221.430,363.53
Cyprus,3409.78,76.520,750.490,2853.590,1135.900,515.61,489.80,0.00,0.00,993.180,551.33,397.600,0.00
Denmark,1384.46,7870.600,16179.100,7595.180,748.000,0.00,2689.61,591.66,2633.03,1725.250,398.20,3876.360,1281.50
EIRE,17198.66,59595.380,19186.860,21865.780,20057.450,18067.95,22562.76,30799.58,22742.46,27545.560,36707.10,27178.440,4726.28
Finland,549.08,658.770,0.000,0.000,1255.130,817.31,534.14,956.23,0.00,864.680,1137.39,414.980,0.00
France,5555.04,8349.010,8981.010,8411.420,7365.110,13400.90,9052.54,11366.75,16148.92,1324.840,14598.33,18848.340,6263.27
Germany,9516.04,11901.210,8871.250,16358.830,23500.491,8702.91,15235.99,18585.15,9772.07,17343.440,21035.40,29626.910,5470.73
Greece,610.95,4798.350,0.000,490.280,277.930,2476.22,302.40,0.00,721.71,780.060,3065.77,761.300,0.00
Iceland,0.00,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.00,0.000,611.53,0.000,711.79
Israel,0.00,0.000,0.000,0.000,0.000,0.00,0.00,1950.98,0.00,0.000,0.00,1248.420,0.00
Italy,398.20,39.670,0.000,734.220,864.990,2349.75,267.45,0.00,0.00,1380.560,4765.97,2562.780,410.80
Japan,-208.75,2.950,156.710,0.000,-2.750,0.00,534.18,617.50,-3.25,1895.000,1533.89,-204.000,4114.48
Korea,0.00,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.00,168.690,-168.69,949.820,0.00
Lithuania,0.00,0.000,0.000,0.000,0.000,0.00,0.00,1706.23,0.00,0.000,0.00,1525.390,1661.06
Malta,0.00,0.000,818.190,0.000,0.000,0.00,0.00,0.00,1868.56,0.000,0.00,0.000,0.00
Netherlands,15204.73,29212.390,15947.310,23959.620,6888.780,22416.53,24102.01,5532.64,24802.49,44986.140,16941.61,33674.910,192.60
Nigeria,0.00,27.820,0.000,0.000,0.000,0.00,0.00,0.00,112.57,0.000,0.00,0.000,0.00
Norway,485.31,0.000,0.000,-5795.870,0.000,0.00,0.00,0.00,0.00,973.690,0.00,4629.320,3787.12
Poland,371.82,0.000,0.000,318.860,0.000,0.00,556.16,341.00,527.44,145.370,0.00,806.140,248.16
Portugal,2821.58,104.590,458.830,2480.800,-38.700,632.95,3646.21,288.10,463.22,2910.180,2902.78,5008.630,1664.52
RSA,0.00,0.000,931.430,0.000,0.000,0.00,0.00,0.00,0.00,0.000,0.00,0.000,0.00
Singapore,0.00,0.000,0.000,0.000,1252.950,0.00,0.00,0.00,0.00,2784.820,0.00,0.000,0.00
Spain,7918.83,2742.350,465.040,1655.070,775.480,2854.58,2332.20,1129.81,1283.49,3749.200,9332.61,2018.750,794.72
Sweden,259.80,1640.150,8202.580,1256.780,15975.440,3556.76,914.30,2489.98,2592.99,2824.370,9316.95,1806.010,0.00
Switzerland,589.40,0.000,477.680,951.620,1902.760,9810.16,2151.27,566.76,1993.65,2474.440,8551.54,13570.730,303.40
Thailand,0.00,0.000,0.000,0.000,0.000,0.00,1956.84,1113.70,0.00,0.000,0.00,0.000,0.00
USA,141.00,2289.590,0.000,0.000,0.000,416.31,896.07,484.25,0.00,-74.200,132.80,269.800,0.00
United Arab Emirates,479.54,0.000,1310.300,1201.520,-16.500,0.00,0.00,0.00,2047.28,0.000,433.60,1713.690,0.00
United Kingdom,589998.06,397681.892,401010.776,546712.111,470317.401,464064.87,472818.70,478660.22,492720.51,652652.211,818534.87,950177.312,270444.51
Unspecified,0.00,998.350,0.000,0.000,252.520,0.00,0.00,1189.94,0.00,1967.950,0.00,300.930,0.00
West Indies,0.00,0.000,0.000,0.000,0.000,0.00,0.00,0.00,536.41,0.000,0.00,0.000,0.00

In [26]:
# 2.2. Yearly Sales Trends with pivot table Country wise

yearly_sales = df.pivot_table(index = df['Country'], values = 'TotalPrice', columns= df['InvoiceDate'].dt.to_period('Y'), aggfunc='sum').fillna(0)
yearly_sales

InvoiceDate                2009         2010
Country
Australia                 50.25    30001.550
Austria                 1998.34    11024.940
Bahrain                    0.00      805.970
Belgium                  447.60    22196.430
Brazil                     0.00      268.270
Canada                     0.00     1216.660
Channel Islands          945.38    20421.940
Cyprus                  3409.78     7764.020
Denmark                 1384.46    45588.490
EIRE                   17198.66   311035.600
Finland                  549.08     6638.630
France                  5555.04   124110.440
Germany                 9516.04   186404.381
Greece                   610.95    13674.020
Iceland                    0.00     1323.320
Israel                     0.00     3199.400
Italy                    398.20    13376.190
Japan                   -208.75     8644.710
Korea                      0.00      949.820
Lithuania                  0.00     4892.680
Malta                      0.00     2686.750
Netherlands            15204.73   248657.030
Nigeria                    0.00      140.390
Norway                   485.31     3594.260
Poland                   371.82     2943.130
Portugal                2821.58    20522.110
RSA                        0.00      931.430
Singapore                  0.00     4037.770
Spain                   7918.83    29133.300
Sweden                   259.80    50576.310
Switzerland              589.40    42754.010
Thailand                   0.00     3070.540
USA                      141.00     4414.620
United Arab Emirates     479.54     6689.890
United Kingdom        589998.06  6415795.383
Unspecified                0.00     4709.690
West Indies                0.00      536.410

In [27]:
# 2.3. Calculating Month over Month Sales Growth Country wise
monthly_sales_growth = monthly_sales.pct_change(axis='columns').fillna(0) * 100
monthly_sales_growth = monthly_sales_growth.round(2)
monthly_sales_growth

# pct_change() function is used to calculate the percentage change between the current and a prior element.
# axis='columns' indicates that the percentage change is calculated across columns (i.e., months) for each row (i.e., country).

InvoiceDate,2009-12,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,2010-07,2010-08,2010-09,2010-10,2010-11,2010-12
Country,,,,,,,,,,,,,
Australia,0.0,-100.00,inf,-58.30,46.94,108.05,142.96,-80.13,-72.22,346.49,280.38,509.13,-96.61
Austria,0.0,-100.00,inf,-17.31,50.09,-58.08,-53.94,-100.00,inf,52.34,-22.18,132.34,-100.00
Bahrain,0.0,0.00,0.00,0.00,0.00,inf,-100.00,0.00,0.00,0.00,inf,-100.00,0.00
Belgium,0.0,262.84,4.70,-47.98,188.19,-96.67,4061.73,-45.86,-10.48,-30.55,24.00,250.90,-93.32
Brazil,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,inf,-100.00,0.00,0.00
Canada,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,inf,-54.27,-100.00
Channel Islands,0.0,-12.96,-100.00,inf,610.42,474.29,-85.93,-104.40,-4230.73,286.71,-18.74,-71.49,-70.24
Cyprus,0.0,-97.76,880.78,280.23,-60.19,-54.61,-5.01,-100.00,0.00,inf,-44.49,-27.88,-100.00
Denmark,0.0,468.50,105.56,-53.06,-90.15,-100.00,inf,-78.00,345.02,-34.48,-76.92,873.47,-66.94
EIRE,0.0,246.51,-67.80,13.96,-8.27,-9.92,24.88,36.51,-26.16,21.12,33.26,-25.96,-82.61
Finland,0.0,19.98,-100.00,0.00,inf,-34.88,-34.65,79.02,-100.00,inf,31.54,-63.51,-100.00
France,0.0,50.30,7.57,-6.34,-12.44,81.95,-32.45,25.56,42.07,-91.80,1001.89,29.11,-66.77
Germany,0.0,25.06,-25.46,84.40,43.66,-62.97,75.07,21.98,-47.42,77.48,21.29,40.84,-81.53
Greece,0.0,685.39,-100.00,inf,-43.31,790.95,-87.79,-100.00,inf,8.08,293.02,-75.17,-100.00
Iceland,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,inf,-100.00,inf
Israel,0.0,0.00,0.00,0.00,0.00,0.00,0.00,inf,-100.00,0.00,0.00,inf,-100.00
Italy,0.0,-90.04,-100.00,inf,17.81,171.65,-88.62,-100.00,0.00,inf,245.22,-46.23,-83.97
Japan,0.0,-101.41,5212.20,-100.00,-inf,-100.00,inf,15.60,-100.53,-58407.69,-19.06,-113.30,-2116.90
Korea,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,inf,-200.00,-663.06,-100.00
Lithuania,0.0,0.00,0.00,0.00,0.00,0.00,0.00,inf,-100.00,0.00,0.00,inf,8.89
Malta,0.0,0.00,inf,-100.00,0.00,0.00,0.00,0.00,inf,-100.00,0.00,0.00,0.00
Netherlands,0.0,92.13,-45.41,50.24,-71.25,225.41,7.52,-77.04,348.29,81.38,-62.34,98.77,-99.43
Nigeria,0.0,inf,-100.00,0.00,0.00,0.00,0.00,0.00,inf,-100.00,0.00,0.00,0.00
Norway,0.0,-100.00,0.00,-inf,-100.00,0.00,0.00,0.00,0.00,inf,-100.00,inf,-18.19
Poland,0.0,-100.00,0.00,inf,-100.00,0.00,inf,-38.69,54.67,-72.44,-100.00,inf,-69.22
Portugal,0.0,-96.29,338.69,440.68,-101.56,-1735.53,476.07,-92.10,60.78,528.25,-0.25,72.55,-66.77
RSA,0.0,0.00,inf,-100.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Singapore,0.0,0.00,0.00,0.00,inf,-100.00,0.00,0.00,0.00,inf,-100.00,0.00,0.00
Spain,0.0,-65.37,-83.04,255.90,-53.15,268.10,-18.30,-51.56,13.60,192.11,148.92,-78.37,-60.63
Sweden,0.0,531.31,400.11,-84.68,1171.14,-77.74,-74.29,172.34,4.14,8.92,229.88,-80.62,-100.00
Switzerland,0.0,-100.00,inf,99.22,99.95,415.58,-78.07,-73.65,251.76,24.12,245.59,58.69,-97.76
Thailand,0.0,0.00,0.00,0.00,0.00,0.00,inf,-43.09,-100.00,0.00,0.00,0.00,0.00
USA,0.0,1523.82,-100.00,0.00,0.00,inf,115.24,-45.96,-100.00,-inf,-278.98,103.16,-100.00
United Arab Emirates,0.0,-100.00,inf,-8.30,-101.37,-100.00,0.00,0.00,inf,-100.00,inf,295.22,-100.00
United Kingdom,0.0,-32.60,0.84,36.33,-13.97,-1.33,1.89,1.24,2.94,32.46,25.42,16.08,-71.54
Unspecified,0.0,inf,-100.00,0.00,inf,-100.00,0.00,inf,-100.00,inf,-100.00,inf,-100.00
West Indies,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,inf,-100.00,0.00,0.00,0.00

In [28]:
# 2.4. Calculating Year over Year Sales Growth
yearly_sales_growth = yearly_sales.pct_change(axis='columns').fillna(0)*100
yearly_sales_growth = yearly_sales_growth.round(2)
yearly_sales_growth

InvoiceDate           2009      2010
Country
Australia              0.0  59604.58
Austria                0.0    451.70
Bahrain                0.0       inf
Belgium                0.0   4858.99
Brazil                 0.0       inf
Canada                 0.0       inf
Channel Islands        0.0   2060.18
Cyprus                 0.0    127.70
Denmark                0.0   3192.87
EIRE                   0.0   1708.49
Finland                0.0   1109.05
France                 0.0   2134.20
Germany                0.0   1858.84
Greece                 0.0   2138.16
Iceland                0.0       inf
Israel                 0.0       inf
Italy                  0.0   3259.16
Japan                  0.0  -4241.18
Korea                  0.0       inf
Lithuania              0.0       inf
Malta                  0.0       inf
Netherlands            0.0   1535.39
Nigeria                0.0       inf
Norway                 0.0    640.61
Poland                 0.0    691.55
Portugal               0.0    627.33
RSA                    0.0       inf
Singapore              0.0       inf
Spain                  0.0    267.90
Sweden                 0.0  19367.40
Switzerland            0.0   7153.82
Thailand               0.0       inf
USA                    0.0   3030.94
United Arab Emirates   0.0   1295.06
United Kingdom         0.0    987.43
Unspecified            0.0       inf
West Indies            0.0       inf

# 📊 Product Analysis

In [29]:
# 3.1. Top 10 Products by TotalPrice
top_10_products_totalprice = df.groupby('Description')['TotalPrice'].sum().sort_values(ascending=False).head(10)
print("Top 10 Products by Total Price:\n", top_10_products_totalprice)

Top 10 Products by Total Price:
 Description
WHITE HANGING HEART T-LIGHT HOLDER     148591.51
REGENCY CAKESTAND 3 TIER               136700.55
ASSORTED COLOUR BIRD ORNAMENT           69652.16
JUMBO BAG RED RETROSPOT                 51493.35
POSTAGE                                 45520.86
ROTATING SILVER ANGELS T-LIGHT HLDR     39871.50
PAPER CHAIN KIT 50'S CHRISTMAS          36804.50
PARTY BUNTING                           34980.10
JUMBO BAG STRAWBERRY                    33862.50
EDWARDIAN PARASOL NATURAL               33541.65
Name: TotalPrice, dtype: float64

In [30]:
# 3.2. Top 10 Products returns by Quantity and Customer ID
product_returns = df[df['Quantity'] < 0].groupby(['Description','Customer ID'])['Quantity'].sum().sort_values().head(10)
print("Top 10 Products Returns:\n", product_returns)

Top 10 Products Returns:
 Description                          Customer ID
ROTATING SILVER ANGELS T-LIGHT HLDR  15838.0       -9360
SET/6 FRUIT SALAD PAPER CUPS         14277.0       -7128
SET/6 FRUIT SALAD  PAPER PLATES      14277.0       -7008
POP ART PEN CASE & PENS              14277.0       -5184
MULTICOLOUR SPRING FLOWER MUG        14277.0       -4992
BLACK SILVER FLOWER T-LIGHT HOLDER   14277.0       -4752
TEATIME PEN CASE & PENS              14277.0       -4608
WHITE BIRD GARDEN DESIGN MUG         14277.0       -4320
S/4 BLUE ROUND DECOUPAGE BOXES       14277.0       -3936
THE KING GIFT BAG                    14277.0       -3744
Name: Quantity, dtype: int64

In [31]:
# 3.3. Calculating low quantity but high returns products

# here we perform groupby on 'Description' and aggregate both 'Quantity' and 'TotalPrice' to identify products with low quantity sold but high returns.
low_quantity_high_returns = df.groupby('Description').agg({'Quantity':'sum', 'TotalPrice' : 'sum' })

# here we filter the products that have low quantity sold but hight returns.
threshold_quantity = low_quantity_high_returns['Quantity'].mean()
threshold_price = low_quantity_high_returns['TotalPrice'].mean()

# here we performing the query to get products with low quantity but high returns.
low_quantity_high_returns = low_quantity_high_returns.query('Quantity < @threshold_quantity and TotalPrice > @threshold_price')
low_quantity_high_returns = low_quantity_high_returns.sort_values(by='Quantity', ascending=True).head(10)
print("Products with Low Quantity but High Returns:\n", low_quantity_high_returns)

Products with Low Quantity but High Returns:
                                      Quantity  TotalPrice
Description
VINTAGE BLUE KITCHEN CABINET               12     4036.50
VINTAGE RED KITCHEN CABINET                14     4130.00
CABIN BAG VINTAGE RETROSPOT               111     3024.45
CARRIAGE                                  115     5885.00
HALL CABINET WITH 3 DRAWERS               116     3913.69
VINTAGE POST OFFICE CABINET               119     7635.07
SWEETHEART CREAM STEEL TABLE RECT         123     2453.85
CHALKBOARD KITCHEN ORGANISER              147     2798.65
EMBOSSED HEART 3 DRAWER SHELF             158     2000.10
SILVER CHRISTMAS TREE BAUBLE STAND        171     2782.45

## 💡 Key Insights

- The United Kingdom contributes the highest share of tatal revenue, making it the primary market.
- A small segment of customers accounts for a large portion of revenue, indicating high-value customers.
- Seasonal spikes are observed during year-end months, suggesting demand peaks.

## 🚀 Business Recommendations
- Target high-value customers with personalized marketng campaigns to increase retention and revenue. 
- Maintain higher inventory levels for top-performing products to avoid stockouts.
- Plan marketing and promotions around year-end to capitalize on seasonal demands.
- Investigate high-return products to reduce losses and imporve proudct quality.